### ISSUE TITLE
Non deterministic drawing of petri nets

### ISSUE THREAD

**Issue by maxhoerstr** [fpom/snakes#27] opened 2023-03-15 21:45 UTC
Hello,

if i execute the following dummy code to draw the created petri net, the result seems to be different in every run.
```python3
def main():
    net = PetriNet("petri_net")
    net.add_place(Place("1", []))
    net.add_place(Place("2", []))
    net.add_place(Place("3", []))
    net.add_transition(Transition("4"))
    net.add_transition(Transition("5"))
    net.add_input("1", "4", Value(1))
    net.add_input("2", "5", Value(1))
    net.add_input("3", "4", Value(1))
    net.add_input("3", "5", Value(1))
    net.draw("petri_net.png", "dot")
```
I need the drawing to be deterministic, so on every run, the same petri net is drawn. Is this possible in the current version of the library?

Below, 2 possible images for the petri net above are shown.

![image](https://user-images.githubusercontent.com/46570215/225449899-82435ac3-2e2d-43dc-b42e-5366216ba0d1.png)
![image](https://user-images.githubusercontent.com/46570215/225450054-001c8ff1-1395-469c-8bfa-d05c45e0886d.png)

Thank you in advance!

**Comment by fpom** [comment] 2023-03-16 10:22
I suspect you're using an old version of Python (2.x) in which `dict` iteration order varies from one execution to another. This may influence the order in which `GraphViz` considers them for computing a layout. On my recent version of Python, the result is deterministic with `dot` layout. However, note that `GraphViz` may use randomized algorithms for other layouts, so the result may be non-deterministic by construction.

I've just committed a patch to plugin `gv` that sorts the nodes provided to `GraphViz`, this should solve your issue if it indeed caused by iteration orders. Let me know if it's better now.

**Comment by maxhoerstr** [comment] 2023-03-16 10:59
Thank you very much for the quick response!
This indeed solved my problem and now all my nets are drawn the same on every run, nice!
I'm using Python 3.10 at the moment, and python version 3.x before, so i dont think Python 2.x was the source of problem. My team members also had the same problems.

Could you update the pip package so we can use the updated version? Thanks in advance!

**Comment by fpom** [comment] 2023-03-16 11:53
My bad, I tested without restarting Python, and indeed iteration order may vary from one execution to another, even with newer Python versions. Anyway, sorting fixes the problem. I'll push a new release on PyPi.

**Closed as completed by fpom** 2023-03-16 11:53 UTC
